### ISSUE TITLE
Change default link variants

### ISSUE THREAD

**Issue by yandodov** [medienbaecker/kirby-link-field#12]
Currently, the plugin will show links for URL, email, page or file if no options are specified in the blueprint. I don't think that makes much sense. You often use the link for a button and you'd want it to point either to an external URL or a page within your own site. I can't think of a usage for file links except when pointing to a download and email links are used for contact links primarily, which are rare.

So my proposal is to have just URL and Page as options when you haven't specified any.

**Comment by medienbaecker** [comment]
I agree, the need for a file button is not that common. I tend to use the email type a lot, though.
In 1.0.1 the default options are `url`, `page` and `email`.

**Comment by yandodov** [comment]
When we're talking about a plugin, I think it's more important to care about the general case. On the web, I can guarantee you that 99% of links are links to other pages and not utility links like mailto and tel.

Anyway, there's no solid answer to this, which is why I think the best option is to define this as a setting in `config/config.php` and give that setting a default of `['url', 'page', 'email']`. Then, in my theme, I set it to `['url', 'page']`. Win/win. Plugins are all about giving you options anyways.
