### ISSUE TITLE
composer setup

### ISSUE THREAD

**Issue by joernroeder** [medienbaecker/kirby-link-field#3]
will you make this plugin available via composer too?

**Comment by medienbaecker** [comment]
I guess my most recent commit should add composer support: https://github.com/medienbaecker/kirby-link-field/commit/ee881d86484768ec9c38a51a4e30a406cb136b8a

Please tell me if that works for you!

**Comment by joernroeder** [comment]
thx i will! there is also the https://github.com/getkirby/pluginkit available now.

**Comment by medienbaecker** [comment]
Yes, that's where I stole the `composer.json` :)

**Comment by joernroeder** [comment]
ah ok great :D

**Comment by medienbaecker** [comment]
@joernroeder I assume the composer support works for you. Closing this issue.
