### ISSUE TITLE
[Feature Request] Shorter button labels

### ISSUE THREAD

**Issue by bavarianbytes** [medienbaecker/kirby-link-field#5]
Great work!

Suggestion for improvement:
Rename the buttons with shorter names, as the whole elements needs a lot of space.

e.g.
URL / Seite / E-Mail

<img width="867" alt="bildschirmfoto 2019-03-08 um 14 34 03" src="https://user-images.githubusercontent.com/17915115/54031518-42f5d480-41af-11e9-9df3-a782cbb7076e.png">

**Comment by macx** [comment]
URL / Page / E-Mail should be really enough.
