### ISSUE TITLE
[Feature Request] Phone Type

### ISSUE THREAD

**Issue by bavarianbytes** [medienbaecker/kirby-link-field#7]
Turning a user input like `(0) 49 123 / 456 78 - 9 ` into `<a href="tel:+49123456789"></a>` via `field()->toHref()` would be great!

**Comment by medienbaecker** [comment]
We'd need a separate "Phone number" option then, right?

**Comment by bavarianbytes** [comment]
> We'd need a separate "Phone number" option then, right?

Yes!

**Comment by medienbaecker** [comment]
I added it as an optional type you can add with the `options:` array.
